<?php

namespace AppBundle\Repository;

/**
 * OlolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OlolRepository extends \Doctrine\ORM\EntityRepository
{
}
