<?php

namespace AppBundle\Repository;

use Symfony\Component\HttpFoundation\Request;
use AppBundle\Entity\Panier;
use AppBundle\Entity\Personne;

/**
 * PanierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PanierRepository extends \Doctrine\ORM\EntityRepository
{
	/**
	 *	Méthode qui créée un nouveau panier ou récupère celui non validé.
	 *
	 *	@return Le nouveau panier ou clui non validé
	 */
	public function panierEnCours(Request $request, $id){

		$session = $request->getSession();
		$em = $this->getEntityManager();
		$panierEnCours = false;

		//on cherche tout les panier de l'utilisateur et on regarde si un est en cours
		$paniers = $em->getRepository(Panier::class)->findBy(array('id_personne' => $id));
		foreach ($paniers as $value){
			if($value->getEtatPanier() == 1){
				$panierEnCours = true;
				$panier = $value;
				break;
			}
		}

		//si pas de panier en cours, on le cree
		if($panierEnCours == false){

			//$personne contient le client actuel (donc ligne a changer)
			$personne = $em->getRepository(Personne::class)->findOneBy(array('id_personne' => $id));

			//on cree un nouveau panier et on remplit ses attributs
			$panier = new Panier();
			$panier->setEtatPanier(1);
			$panier->setIdPersonne($personne);
			$date = new \DateTime('now');
			$panier->setDatePanier($date);

			// enregistrer les donnees dans la base
			$em->persist($panier);
			$em->flush();
		}

		return $panier;
	}

}