<?php

namespace AppBundle\Repository;

/**
 * PersonneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonneRepository extends \Doctrine\ORM\EntityRepository
{
    public function findList(){

          $orderby = array('idPersonne' => 'ASC');

          return $this->findBy(array(), $orderby);
      }

      public function findById($ref){

          $keys = array("idPersonne" => $ref);
          $orderby = array('idPersonne' => 'ASC');

          return $this->find($keys, $orderby);
      }
}
