<?php

namespace AppBundle\Repository;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

use AppBundle\Entity\Personne;
/**
 * PersonneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonneRepository extends \Doctrine\ORM\EntityRepository
{
	public function findList(){

        $orderby = array('ref_produit' => 'ASC');

        return $this->findBy(array(), $orderby);
    }

    public function getIdSession($user){
        $em = $this->getEntityManager();

        $p = $em->getRepository(Personne::class)->findOneBy(array('pseudo_personne'=>$user));
        return $p->getIdPersonne();
    }
}
