<?php

namespace AppBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
  public function findList(){

        $orderby = array('ref_produit' => 'ASC');

        return $this->findBy(array(), $orderby);
    }

    public function findById($ref){

        $keys = array("ref_produit" => $ref);
        $orderby = array('ref_produit' => 'ASC');

        return $this->find($keys, $orderby);
    }
}
